### ISSUE TITLE
Version of Zimbra

### ISSUE THREAD

**Issue by sayntabey** [Zimbra-Community/zimbra-elasticstack#1]
Which version of zimbra was the above tested on, presently using 8.6.0 GA but the pattern files seems not to be working. By the way is a multi-server installation.

**Comment by barrydegraaff** [comment]
THIS IS A WORK IN PROGRESS - NOT PRODUCTION READY 

In any case, it is probably developed on 8.8 and won't support 8.6 


Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
