### ISSUE TITLE
nothing see on dashboards

### ISSUE THREAD

**Issue by fferraro87** [Zimbra-Community/zimbra-elasticstack#3]
Hi,
i'm new on elk stack. and i've some questions :
1) i've correctly connect my zimbra server trough filebeat to my elastic server, so i can see /opt/zimbra/log/mailbox.log on my kibana but i cannot see anything on dashboard.
i've import saved objects and add pattern and filter on logstash
2) where i can upload index_template_creation? i've created from index management -> index templates, it's correct?
3) for maps i need to install geoip on elastic server (centos7)? or something else?

Thanks

**Comment by barrydegraaff** [comment]
@pupseba can you answer this question?

**Comment by pupseba** [comment]
Sure @barrydegraaff sorry my delay.

Hi @fferraro87,

I understand your problems. 
1. The integration done here is for a pre 7.x Elastic Stack version. As they are trying to implement ECS, they had changed some of the field names which also happen to be used in the grok filters. So, what it used to be called "[source]" in the logstash filter, is now called "[file][log][path]" (they use this pythonic way of calling the field you see in elastic as "log.path.file".

2. Go to the "debugger" in kibana and just "copy/paste" the whole text in there and then execute it. It is a "PUT" statement which will add the correct template once excecuted.

3. The plugin is native now, no need to manually install it anymore (if >7.x)

Hope this helps!!!

**Comment by fferraro87** [comment]
Thanks a lot!!!
