### ISSUE TITLE
Use this pattern in ELK 7.8

### ISSUE THREAD

**Issue by Shpil93** [Zimbra-Community/zimbra-elasticstack#4]
Hi. I'm new user to ELK. I want to set up Zimbra monitoring in ELK 7.8. When can I use your template in ELK 7.8? 
Thank you very much for your attention.

**Comment by eniserkaya** [comment]
Just change logstash conf like this pull request.

In this repo, monitoring dashboards use the tags field in elasticsearch logs, but in ELK 7.10.1 version, the if condition in logstash conf, does not work in my case. I just changed the source keyword as in this #5

**Comment by barrydegraaff** [comment]
this has now been merged/fixed.
